/**
 * Campaign Proposal data model.
 *
 * A CampaignProposal represents a complete, ready-to-review Google Ads
 * Search campaign structure generated by the system. It includes:
 *   - Campaign-level settings (name, market, objective, bidding, budget)
 *   - Ad groups with wholesaling-specific themes
 *   - Keywords per ad group (exact, phrase, broad)
 *   - Shared negative keywords
 *   - RSA (Responsive Search Ad) copy per ad group
 *   - Landing page recommendation
 *   - Per-ad-group rationale
 *
 * The operator reviews and acts on proposals before anything is deployed.
 * This model is intentionally read-only — no Google Ads write actions exist.
 */

import type { Market } from './markets';
import type { SellerSituation } from './seller-situations';
import type { RiskLevel } from './recommendations';

// ── Proposal lifecycle ──────────────────────────────────────────

export type ProposalStatus =
  | 'draft'
  | 'pending_review'
  | 'approved'
  | 'edits_requested'
  | 'rejected'
  | 'deployed';

export const PROPOSAL_STATUS_LABELS: Record<ProposalStatus, string> = {
  draft: 'Draft',
  pending_review: 'Pending Review',
  approved: 'Approved',
  edits_requested: 'Edits Requested',
  rejected: 'Rejected',
  deployed: 'Deployed',
};

// ── Keyword match types ─────────────────────────────────────────

export type KeywordMatchType = 'EXACT' | 'PHRASE' | 'BROAD';

export interface ProposalKeyword {
  text: string;
  match_type: KeywordMatchType;
  /** Estimated monthly search volume range, if known */
  estimated_volume?: string;
}

// ── Negative keywords ───────────────────────────────────────────

export interface ProposalNegativeKeyword {
  text: string;
  match_type: KeywordMatchType;
  /** Why this negative is included */
  reason: string;
}

// ── RSA (Responsive Search Ad) ──────────────────────────────────

export interface ProposalRSA {
  /** Up to 15 headlines, each max 30 characters */
  headlines: string[];
  /** Up to 4 descriptions, each max 90 characters */
  descriptions: string[];
  /** Final URL — the landing page for this ad group */
  final_url: string;
  /** Display path segments (e.g., ["Sell-House", "Fast"]) */
  display_path?: [string, string?];
}

// ── Ad group ────────────────────────────────────────────────────

export type AdGroupTheme =
  | 'generic_seller_intent'
  | 'as_is_repairs'
  | 'inherited_probate'
  | 'landlord_tenant'
  | 'urgent_sale';

export const AD_GROUP_THEME_LABELS: Record<AdGroupTheme, string> = {
  generic_seller_intent: 'Generic Seller Intent',
  as_is_repairs: 'As-Is / Repairs Needed',
  inherited_probate: 'Inherited / Probate',
  landlord_tenant: 'Landlord / Tenant Issues',
  urgent_sale: 'Urgent Sale',
};

export const AD_GROUP_THEME_DESCRIPTIONS: Record<AdGroupTheme, string> = {
  generic_seller_intent:
    'Broad seller intent — people searching for ways to sell their house, looking for buyers, or exploring their options.',
  as_is_repairs:
    'Sellers with properties needing major work — foundation issues, mold, fire damage, outdated homes they cannot afford to fix.',
  inherited_probate:
    'Heirs dealing with inherited properties or probate estates — often out-of-state, unfamiliar with the process, and motivated to close quickly.',
  landlord_tenant:
    'Tired landlords, problem tenants, or rental property owners who want out — motivated by management fatigue or financial strain.',
  urgent_sale:
    'Sellers under time pressure — facing foreclosure, divorce, relocation, or simply need cash fast. Highest urgency, highest conversion intent.',
};

/** Maps ad group themes to related seller situations for targeting context */
export const AD_GROUP_SELLER_SITUATIONS: Record<AdGroupTheme, SellerSituation[]> = {
  generic_seller_intent: ['unknown', 'low_intent'],
  as_is_repairs: ['major_repairs', 'foundation_mold_damage'],
  inherited_probate: ['inherited', 'probate'],
  landlord_tenant: ['tired_landlord', 'tenant_issues'],
  urgent_sale: ['foreclosure', 'divorce', 'relocation', 'vacant_property'],
};

export interface ProposalAdGroup {
  /** Internal identifier within the proposal */
  id: string;
  /** Display name for the ad group */
  name: string;
  /** Thematic grouping */
  theme: AdGroupTheme;
  /** Keywords to target */
  keywords: ProposalKeyword[];
  /** Responsive Search Ad copy */
  rsa: ProposalRSA;
  /** Why this ad group exists and the strategy behind it */
  rationale: string;
  /** Expected relative performance */
  expected_performance: 'high' | 'medium' | 'low';
}

// ── Campaign-level settings ─────────────────────────────────────

export type BiddingStrategy =
  | 'MAXIMIZE_CONVERSIONS'
  | 'MAXIMIZE_CLICKS'
  | 'TARGET_CPA'
  | 'MANUAL_CPC';

export const BIDDING_STRATEGY_LABELS: Record<BiddingStrategy, string> = {
  MAXIMIZE_CONVERSIONS: 'Maximize Conversions',
  MAXIMIZE_CLICKS: 'Maximize Clicks',
  TARGET_CPA: 'Target CPA',
  MANUAL_CPC: 'Manual CPC',
};

export type CampaignObjective =
  | 'lead_generation'
  | 'website_traffic'
  | 'brand_awareness';

export const CAMPAIGN_OBJECTIVE_LABELS: Record<CampaignObjective, string> = {
  lead_generation: 'Lead Generation',
  website_traffic: 'Website Traffic',
  brand_awareness: 'Brand Awareness',
};

// ── Main proposal interface ─────────────────────────────────────

export interface CampaignProposal {
  /** Unique identifier */
  id: string;
  /** Human-readable proposal name */
  name: string;
  /** Version number — increments on edits */
  version: number;

  // ── Campaign settings ───────────────────────────────────────
  campaign_name: string;
  market: Market;
  objective: CampaignObjective;
  bidding_strategy: BiddingStrategy;
  /** Recommended daily budget in dollars */
  daily_budget_dollars: number;
  /** Bidding target (e.g., target CPA in dollars) — only for TARGET_CPA */
  bidding_target_dollars?: number;

  // ── Structure ───────────────────────────────────────────────
  ad_groups: ProposalAdGroup[];
  negative_keywords: ProposalNegativeKeyword[];

  // ── Landing page ────────────────────────────────────────────
  landing_page_recommendation: {
    url: string;
    rationale: string;
  };

  // ── Metadata ────────────────────────────────────────────────
  risk_level: RiskLevel;
  status: ProposalStatus;
  /** Overall rationale for the campaign */
  campaign_rationale: string;
  /** Assumptions or caveats the operator should know */
  assumptions: string[];
  /** Operator notes — editable by the operator */
  operator_notes?: string;

  // ── Timestamps ──────────────────────────────────────────────
  created_at: string;
  updated_at: string;
}
